// <auto-generated />
using System;
using GameAuthAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameAuthAPI.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250216113915_AddGuildsAndGroupQuests")]
    partial class AddGuildsAndGroupQuests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameAuthAPI.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementBonuses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BossKills")
                        .HasColumnType("int");

                    b.Property<bool>("CanBeUpgraded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPartOfSet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuestItem")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUpgradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlayerKills")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Mob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpawnLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpawnLocationId");

                    b.ToTable("Mobs");
                });

            modelBuilder.Entity("GameAuthAPI.Models.NPC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dialogue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpawnLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpawnLocationId");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerKills")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerGuild", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GuildId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("PlayerGuilds");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerItem", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<int?>("PlayerTradeId1")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerTradeId2")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerTradeId1");

                    b.HasIndex("PlayerTradeId2");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmedByPlayer1")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmedByPlayer2")
                        .HasColumnType("bit");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("PlayerTrades");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGroupQuest")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredPlayers")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("GameAuthAPI.Models.QuestParticipant", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("QuestId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("QuestParticipants");
                });

            modelBuilder.Entity("LocationLocation", b =>
                {
                    b.Property<int>("ConnectedLocationsId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("ConnectedLocationsId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationConnections", (string)null);
                });

            modelBuilder.Entity("GameAuthAPI.Models.ChatMessage", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Player", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameAuthAPI.Models.Player", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Mob", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Location", "SpawnLocation")
                        .WithMany()
                        .HasForeignKey("SpawnLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpawnLocation");
                });

            modelBuilder.Entity("GameAuthAPI.Models.NPC", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Location", "SpawnLocation")
                        .WithMany()
                        .HasForeignKey("SpawnLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpawnLocation");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Player", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerGuild", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Guild", "Guild")
                        .WithMany("PlayerGuilds")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Player", "Player")
                        .WithMany("PlayerGuilds")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerItem", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Player", "Player")
                        .WithMany("PlayerItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.PlayerTrade", null)
                        .WithMany("Player1Items")
                        .HasForeignKey("PlayerTradeId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameAuthAPI.Models.PlayerTrade", null)
                        .WithMany("Player2Items")
                        .HasForeignKey("PlayerTradeId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerTrade", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Quest", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Player", null)
                        .WithMany("Quests")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("GameAuthAPI.Models.QuestParticipant", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Quest", "Quest")
                        .WithMany("QuestParticipants")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("LocationLocation", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("ConnectedLocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameAuthAPI.Models.Guild", b =>
                {
                    b.Navigation("PlayerGuilds");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Player", b =>
                {
                    b.Navigation("PlayerGuilds");

                    b.Navigation("PlayerItems");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerTrade", b =>
                {
                    b.Navigation("Player1Items");

                    b.Navigation("Player2Items");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Quest", b =>
                {
                    b.Navigation("QuestParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
