// <auto-generated />
using GameAuthAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameAuthAPI.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250207212127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameAuthAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerItem", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerTradeId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerTradeId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerTradeId");

                    b.HasIndex("PlayerTradeId1");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmedByPlayer1")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmedByPlayer2")
                        .HasColumnType("bit");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("PlayerTrades");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerItem", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Player", "Player")
                        .WithMany("PlayerItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.PlayerTrade", null)
                        .WithMany("Player1Items")
                        .HasForeignKey("PlayerTradeId");

                    b.HasOne("GameAuthAPI.Models.PlayerTrade", null)
                        .WithMany("Player2Items")
                        .HasForeignKey("PlayerTradeId1");

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerTrade", b =>
                {
                    b.HasOne("GameAuthAPI.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameAuthAPI.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("GameAuthAPI.Models.Player", b =>
                {
                    b.Navigation("PlayerItems");
                });

            modelBuilder.Entity("GameAuthAPI.Models.PlayerTrade", b =>
                {
                    b.Navigation("Player1Items");

                    b.Navigation("Player2Items");
                });
#pragma warning restore 612, 618
        }
    }
}
